import type { APIRoute } from "astro";
import config from "../../../school.config";

export const GET: APIRoute = (context) => {
	const origin = new URL(context.request.url).origin;

	const spec = {
		openapi: "3.1.0",
		info: {
			title: `${config.name} API`,
			description: `API for fetching lesson and exercise content, enrolling students, and tracking progress through ${config.name}.`,
			version: "1.0.0",
		},
		servers: [{ url: origin }],
		paths: {
			"/api/lessons": {
				get: {
					summary: "List all lessons",
					description:
						"Returns all lessons sorted by order, including content (as prose markdown) and agent instructions.",
					responses: {
						"200": {
							description: "Array of all lessons",
							content: {
								"application/json": {
									schema: {
										type: "array",
										items: { $ref: "#/components/schemas/Lesson" },
									},
								},
							},
						},
					},
				},
			},
			"/api/lessons/{slug}": {
				get: {
					summary: "Get a single lesson",
					description:
						"Returns a single lesson by slug, including content (as prose markdown) and agent instructions.",
					parameters: [
						{
							name: "slug",
							in: "path",
							required: true,
							schema: { type: "string" },
						},
					],
					responses: {
						"200": {
							description: "Lesson found",
							content: {
								"application/json": {
									schema: { $ref: "#/components/schemas/Lesson" },
								},
							},
						},
						"404": {
							description: "Lesson not found",
							content: {
								"application/json": {
									schema: { $ref: "#/components/schemas/Error" },
								},
							},
						},
					},
				},
			},
			"/api/exercises": {
				get: {
					summary: "List all exercises",
					description:
						"Returns all exercises sorted by order, including content (as prose markdown) and agent instructions.",
					responses: {
						"200": {
							description: "Array of all exercises",
							content: {
								"application/json": {
									schema: {
										type: "array",
										items: { $ref: "#/components/schemas/Exercise" },
									},
								},
							},
						},
					},
				},
			},
			"/api/exercises/{slug}": {
				get: {
					summary: "Get a single exercise",
					description:
						"Returns a single exercise by slug, including content (as prose markdown) and agent instructions.",
					parameters: [
						{
							name: "slug",
							in: "path",
							required: true,
							schema: { type: "string" },
						},
					],
					responses: {
						"200": {
							description: "Exercise found",
							content: {
								"application/json": {
									schema: { $ref: "#/components/schemas/Exercise" },
								},
							},
						},
						"404": {
							description: "Exercise not found",
							content: {
								"application/json": {
									schema: { $ref: "#/components/schemas/Error" },
								},
							},
						},
					},
				},
			},
			"/api/enroll": {
				post: {
					summary: "Enroll a new student",
					description:
						"Generates a unique student ID (format: adjective-noun-nnnn) and creates an empty progress record.",
					requestBody: {
						required: false,
						content: {
							"application/json": {
								schema: {
									type: "object",
									properties: {
										deviceId: {
											type: "string",
											format: "uuid",
											description:
												"Anonymous device identifier generated by the client.",
										},
									},
								},
							},
						},
					},
					responses: {
						"201": {
							description: "Student enrolled",
							content: {
								"application/json": {
									schema: {
										type: "object",
										properties: {
											studentId: { type: "string" },
											progress: { $ref: "#/components/schemas/Progress" },
										},
										required: ["studentId", "progress"],
									},
								},
							},
						},
					},
				},
			},
			"/api/progress/{studentId}": {
				get: {
					summary: "Get student progress",
					description:
						"Returns the student's progress, including which lessons and exercises they have completed.",
					parameters: [
						{
							name: "studentId",
							in: "path",
							required: true,
							schema: { type: "string" },
						},
					],
					responses: {
						"200": {
							description: "Progress found",
							content: {
								"application/json": {
									schema: { $ref: "#/components/schemas/Progress" },
								},
							},
						},
						"400": {
							description: "Invalid student ID format",
							content: {
								"application/json": {
									schema: { $ref: "#/components/schemas/Error" },
								},
							},
						},
						"404": {
							description: "Student not found",
							content: {
								"application/json": {
									schema: { $ref: "#/components/schemas/Error" },
								},
							},
						},
					},
				},
				put: {
					summary: "Mark a lesson or exercise as complete",
					description:
						"Marks a lesson or exercise as complete for the given student. Supply either lessonSlug or exerciseSlug (not both). Idempotent.",
					parameters: [
						{
							name: "studentId",
							in: "path",
							required: true,
							schema: { type: "string" },
						},
					],
					requestBody: {
						required: true,
						content: {
							"application/json": {
								schema: {
									type: "object",
									properties: {
										lessonSlug: {
											type: "string",
											description: "Slug of the lesson to mark complete.",
										},
										exerciseSlug: {
											type: "string",
											description: "Slug of the exercise to mark complete.",
										},
										source: {
											type: "string",
											enum: ["browser", "agent"],
											description: "Who marked the item complete.",
										},
										model: {
											type: "string",
											description:
												"The model ID used by the agent. Agents should always include this.",
										},
									},
								},
							},
						},
					},
					responses: {
						"200": {
							description: "Progress updated",
							content: {
								"application/json": {
									schema: { $ref: "#/components/schemas/Progress" },
								},
							},
						},
						"400": {
							description: "Invalid request",
							content: {
								"application/json": {
									schema: { $ref: "#/components/schemas/Error" },
								},
							},
						},
						"404": {
							description: "Student not found",
							content: {
								"application/json": {
									schema: { $ref: "#/components/schemas/Error" },
								},
							},
						},
					},
				},
				delete: {
					summary: "Undo a completion or reset all progress",
					description:
						'Send { "lessonSlug": "..." } to uncomplete a lesson, { "exerciseSlug": "..." } to uncomplete an exercise, or { "reset": true } to clear all completions.',
					parameters: [
						{
							name: "studentId",
							in: "path",
							required: true,
							schema: { type: "string" },
						},
					],
					requestBody: {
						required: true,
						content: {
							"application/json": {
								schema: {
									type: "object",
									properties: {
										lessonSlug: { type: "string" },
										exerciseSlug: { type: "string" },
										reset: { type: "boolean" },
									},
								},
							},
						},
					},
					responses: {
						"200": {
							description: "Progress updated",
							content: {
								"application/json": {
									schema: { $ref: "#/components/schemas/Progress" },
								},
							},
						},
						"400": {
							description: "Invalid request",
							content: {
								"application/json": {
									schema: { $ref: "#/components/schemas/Error" },
								},
							},
						},
						"404": {
							description: "Student not found",
							content: {
								"application/json": {
									schema: { $ref: "#/components/schemas/Error" },
								},
							},
						},
					},
				},
			},
			"/api/profile/{studentId}": {
				get: {
					summary: "Get student profile",
					description:
						"Returns the student's profile from the interview lesson.",
					parameters: [
						{
							name: "studentId",
							in: "path",
							required: true,
							schema: { type: "string" },
						},
					],
					responses: {
						"200": {
							description: "Profile found",
							content: {
								"application/json": {
									schema: {
										type: "object",
										properties: {
											profile: {
												$ref: "#/components/schemas/StudentProfile",
											},
										},
										required: ["profile"],
									},
								},
							},
						},
						"404": {
							description: "Student not found",
							content: {
								"application/json": {
									schema: { $ref: "#/components/schemas/Error" },
								},
							},
						},
					},
				},
				put: {
					summary: "Update student profile",
					description:
						"Merges new profile fields into the student's existing profile. Partial updates are supported.",
					parameters: [
						{
							name: "studentId",
							in: "path",
							required: true,
							schema: { type: "string" },
						},
					],
					requestBody: {
						required: true,
						content: {
							"application/json": {
								schema: {
									$ref: "#/components/schemas/StudentProfile",
								},
							},
						},
					},
					responses: {
						"200": {
							description: "Profile updated",
							content: {
								"application/json": {
									schema: {
										type: "object",
										properties: {
											profile: {
												$ref: "#/components/schemas/StudentProfile",
											},
										},
										required: ["profile"],
									},
								},
							},
						},
						"400": {
							description: "Invalid request",
							content: {
								"application/json": {
									schema: { $ref: "#/components/schemas/Error" },
								},
							},
						},
						"404": {
							description: "Student not found",
							content: {
								"application/json": {
									schema: { $ref: "#/components/schemas/Error" },
								},
							},
						},
					},
				},
			},
		},
		components: {
			schemas: {
				Lesson: {
					type: "object",
					properties: {
						order: { type: "integer" },
						slug: { type: "string" },
						title: { type: "string" },
						description: { type: "string" },
						agentOnly: { type: "boolean" },
						agentInstructions: { type: "string" },
						content: {
							type: "string",
							description:
								"Lesson content as prose markdown (HTML and scripts stripped).",
						},
					},
					required: [
						"order",
						"slug",
						"title",
						"description",
						"agentOnly",
						"agentInstructions",
						"content",
					],
				},
				Exercise: {
					type: "object",
					properties: {
						order: { type: "integer" },
						slug: { type: "string" },
						title: { type: "string" },
						description: { type: "string" },
						agentInstructions: { type: "string" },
						content: {
							type: "string",
							description:
								"Exercise content as prose markdown (HTML and scripts stripped).",
						},
					},
					required: [
						"order",
						"slug",
						"title",
						"description",
						"agentInstructions",
						"content",
					],
				},
				CompletedLesson: {
					type: "object",
					properties: {
						slug: { type: "string" },
						completedAt: { type: "string", format: "date-time" },
						source: { type: "string", enum: ["browser", "agent"] },
						model: { type: "string" },
					},
					required: ["slug", "completedAt", "source"],
				},
				CompletedExercise: {
					type: "object",
					properties: {
						slug: { type: "string" },
						completedAt: { type: "string", format: "date-time" },
						source: { type: "string", enum: ["browser", "agent"] },
						model: { type: "string" },
					},
					required: ["slug", "completedAt", "source"],
				},
				StudentProfile: {
					type: "object",
					description:
						"Student preferences from the interview lesson. All fields are optional and defined in school.config.ts.",
					properties: Object.fromEntries(
						Object.entries(config.profileFields).map(([fieldName, field]) => [
							fieldName,
							field.type === "multi"
								? {
										type: "array",
										items: {
											type: "string",
											enum: field.options.map((o) => o.value),
										},
									}
								: {
										type: "string",
										enum: field.options.map((o) => o.value),
									},
						]),
					),
				},
				Progress: {
					type: "object",
					properties: {
						completedLessons: {
							type: "array",
							items: { $ref: "#/components/schemas/CompletedLesson" },
						},
						completedExercises: {
							type: "array",
							items: { $ref: "#/components/schemas/CompletedExercise" },
						},
						profile: { $ref: "#/components/schemas/StudentProfile" },
						createdAt: { type: "string", format: "date-time" },
						updatedAt: { type: "string", format: "date-time" },
						deviceId: { type: "string", format: "uuid" },
					},
					required: [
						"completedLessons",
						"completedExercises",
						"createdAt",
						"updatedAt",
					],
				},
				Error: {
					type: "object",
					properties: {
						error: { type: "string" },
					},
					required: ["error"],
				},
			},
		},
	};

	return new Response(JSON.stringify(spec, null, 2), {
		status: 200,
		headers: { "Content-Type": "application/json" },
	});
};
